name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  test-and-export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install backend requirements
        run: |
          python -m pip install --upgrade pip
          if [ -f ProjectSynapse/backend/requirements.txt ]; then pip install -r ProjectSynapse/backend/requirements.txt; fi
      - name: Run tests
        working-directory: ProjectSynapse/backend
        run: |
          python -m pytest -q
      - name: Export OpenAPI
        run: |
          python ../../scripts/export_openapi.py --backend-dir ProjectSynapse/backend --out docs/external/openapi.json
      - name: Upload OpenAPI artifact
        uses: actions/upload-artifact@v4
        with:
          name: openapi-json
          path: docs/external/openapi.json
